name: destroyer
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  audioplayers: ^5.2.1
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flame_behaviors: ^1.1.0
  flame_rive: ^1.10.0
  flame_steering_behaviors: ^0.1.0
  flame_tiled: ^1.19.0
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  logging: ^1.2.0
  nes_ui: ^0.15.0
  provider: ^6.1.2
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  web: ^0.5.0

dev_dependencies:
  flame_test: ^1.15.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  # flutter_test:
  #   sdk: flutter
  # test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/npcs/
    - assets/images/enemies/
    - assets/images/hud/
    - assets/images/skills-and-effects/
    - assets/images/equipments/swords/
    - assets/images/equipments/armors/
    - assets/tiles/
    - assets/animations/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/icon.png'
